        FROM php:7.3-fpm-alpine
        ENV TERM=xterm
        RUN apk add bash mysql-client
        RUN docker-php-ext-install pdo pdo_mysql

        WORKDIR /var/www
        RUN rm -rf /var/www/html
        
        # Install composer
        RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
        
        #Essa função só uso quando quero instalar instância do composer da minha aplicação como laravel.
        #RUN composer install

        COPY .  /var/www               

        RUN ln -s public html        
        
        RUN rm -rf /var/lib/apt/lists/*

        # Expose port 9000 and start php-fpm server
        EXPOSE 9000
                